packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  bcrypt: true
  prisma: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@nestjs/common@11.1.24'
  - '@nestjs/core@11.1.24'
  - '@nestjs/platform-express@11.1.24'
  - '@nestjs/testing@11.1.24'
