/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OrganizationProtectedRouteImport } from './routes/_organization-protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyEmailRouteImport } from './routes/verify/email'
import { Route as OnboardingUserRouteImport } from './routes/onboarding/user'
import { Route as OnboardingSuccessRouteImport } from './routes/onboarding/success'
import { Route as OnboardingOrganizationRouteImport } from './routes/onboarding/organization'
import { Route as AuthSetPasswordRouteImport } from './routes/auth/set-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as OrganizationProtectedSelectOrganizationRouteImport } from './routes/_organization-protected/select-organization'
import { Route as OrganizationProtectedOrganizationRouteImport } from './routes/_organization-protected/$organization'
import { Route as OrganizationProtectedOrganizationVisitorRouteImport } from './routes/_organization-protected/$organization/visitor'
import { Route as OrganizationProtectedOrganizationTicketRouteImport } from './routes/_organization-protected/$organization/ticket'
import { Route as OrganizationProtectedOrganizationSettingsRouteImport } from './routes/_organization-protected/$organization/settings'
import { Route as OrganizationProtectedOrganizationPluginsRouteImport } from './routes/_organization-protected/$organization/plugins'
import { Route as OrganizationProtectedOrganizationLiveVisitorRouteImport } from './routes/_organization-protected/$organization/live-visitor'
import { Route as OrganizationProtectedOrganizationInboxRouteImport } from './routes/_organization-protected/$organization/inbox'
import { Route as OrganizationProtectedOrganizationDashboardRouteImport } from './routes/_organization-protected/$organization/dashboard'
import { Route as OrganizationProtectedOrganizationSettingsTeamManagementRouteImport } from './routes/_organization-protected/$organization/settings/team-management'
import { Route as OrganizationProtectedOrganizationSettingsOrganizationSettingsOrganizationInformationRouteImport } from './routes/_organization-protected/$organization/settings/organization-settings/organization-information'
import { Route as OrganizationProtectedOrganizationSettingsAccountSettingsSecurityRouteImport } from './routes/_organization-protected/$organization/settings/account-settings/security'
import { Route as OrganizationProtectedOrganizationSettingsAccountSettingsAccountInformationRouteImport } from './routes/_organization-protected/$organization/settings/account-settings/account-information'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationProtectedRoute = OrganizationProtectedRouteImport.update({
  id: '/_organization-protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => VerifyRoute,
} as any)
const OnboardingUserRoute = OnboardingUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingSuccessRoute = OnboardingSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingOrganizationRoute = OnboardingOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => OnboardingRoute,
} as any)
const AuthSetPasswordRoute = AuthSetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const OrganizationProtectedSelectOrganizationRoute =
  OrganizationProtectedSelectOrganizationRouteImport.update({
    id: '/select-organization',
    path: '/select-organization',
    getParentRoute: () => OrganizationProtectedRoute,
  } as any)
const OrganizationProtectedOrganizationRoute =
  OrganizationProtectedOrganizationRouteImport.update({
    id: '/$organization',
    path: '/$organization',
    getParentRoute: () => OrganizationProtectedRoute,
  } as any)
const OrganizationProtectedOrganizationVisitorRoute =
  OrganizationProtectedOrganizationVisitorRouteImport.update({
    id: '/visitor',
    path: '/visitor',
    getParentRoute: () => OrganizationProtectedOrganizationRoute,
  } as any)
const OrganizationProtectedOrganizationTicketRoute =
  OrganizationProtectedOrganizationTicketRouteImport.update({
    id: '/ticket',
    path: '/ticket',
    getParentRoute: () => OrganizationProtectedOrganizationRoute,
  } as any)
const OrganizationProtectedOrganizationSettingsRoute =
  OrganizationProtectedOrganizationSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => OrganizationProtectedOrganizationRoute,
  } as any)
const OrganizationProtectedOrganizationPluginsRoute =
  OrganizationProtectedOrganizationPluginsRouteImport.update({
    id: '/plugins',
    path: '/plugins',
    getParentRoute: () => OrganizationProtectedOrganizationRoute,
  } as any)
const OrganizationProtectedOrganizationLiveVisitorRoute =
  OrganizationProtectedOrganizationLiveVisitorRouteImport.update({
    id: '/live-visitor',
    path: '/live-visitor',
    getParentRoute: () => OrganizationProtectedOrganizationRoute,
  } as any)
const OrganizationProtectedOrganizationInboxRoute =
  OrganizationProtectedOrganizationInboxRouteImport.update({
    id: '/inbox',
    path: '/inbox',
    getParentRoute: () => OrganizationProtectedOrganizationRoute,
  } as any)
const OrganizationProtectedOrganizationDashboardRoute =
  OrganizationProtectedOrganizationDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => OrganizationProtectedOrganizationRoute,
  } as any)
const OrganizationProtectedOrganizationSettingsTeamManagementRoute =
  OrganizationProtectedOrganizationSettingsTeamManagementRouteImport.update({
    id: '/team-management',
    path: '/team-management',
    getParentRoute: () => OrganizationProtectedOrganizationSettingsRoute,
  } as any)
const OrganizationProtectedOrganizationSettingsOrganizationSettingsOrganizationInformationRoute =
  OrganizationProtectedOrganizationSettingsOrganizationSettingsOrganizationInformationRouteImport.update(
    {
      id: '/organization-settings/organization-information',
      path: '/organization-settings/organization-information',
      getParentRoute: () => OrganizationProtectedOrganizationSettingsRoute,
    } as any,
  )
const OrganizationProtectedOrganizationSettingsAccountSettingsSecurityRoute =
  OrganizationProtectedOrganizationSettingsAccountSettingsSecurityRouteImport.update(
    {
      id: '/account-settings/security',
      path: '/account-settings/security',
      getParentRoute: () => OrganizationProtectedOrganizationSettingsRoute,
    } as any,
  )
const OrganizationProtectedOrganizationSettingsAccountSettingsAccountInformationRoute =
  OrganizationProtectedOrganizationSettingsAccountSettingsAccountInformationRouteImport.update(
    {
      id: '/account-settings/account-information',
      path: '/account-settings/account-information',
      getParentRoute: () => OrganizationProtectedOrganizationSettingsRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/verify': typeof VerifyRouteWithChildren
  '/$organization': typeof OrganizationProtectedOrganizationRouteWithChildren
  '/select-organization': typeof OrganizationProtectedSelectOrganizationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/onboarding/organization': typeof OnboardingOrganizationRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/onboarding/user': typeof OnboardingUserRoute
  '/verify/email': typeof VerifyEmailRoute
  '/$organization/dashboard': typeof OrganizationProtectedOrganizationDashboardRoute
  '/$organization/inbox': typeof OrganizationProtectedOrganizationInboxRoute
  '/$organization/live-visitor': typeof OrganizationProtectedOrganizationLiveVisitorRoute
  '/$organization/plugins': typeof OrganizationProtectedOrganizationPluginsRoute
  '/$organization/settings': typeof OrganizationProtectedOrganizationSettingsRouteWithChildren
  '/$organization/ticket': typeof OrganizationProtectedOrganizationTicketRoute
  '/$organization/visitor': typeof OrganizationProtectedOrganizationVisitorRoute
  '/$organization/settings/team-management': typeof OrganizationProtectedOrganizationSettingsTeamManagementRoute
  '/$organization/settings/account-settings/account-information': typeof OrganizationProtectedOrganizationSettingsAccountSettingsAccountInformationRoute
  '/$organization/settings/account-settings/security': typeof OrganizationProtectedOrganizationSettingsAccountSettingsSecurityRoute
  '/$organization/settings/organization-settings/organization-information': typeof OrganizationProtectedOrganizationSettingsOrganizationSettingsOrganizationInformationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/verify': typeof VerifyRouteWithChildren
  '/$organization': typeof OrganizationProtectedOrganizationRouteWithChildren
  '/select-organization': typeof OrganizationProtectedSelectOrganizationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/onboarding/organization': typeof OnboardingOrganizationRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/onboarding/user': typeof OnboardingUserRoute
  '/verify/email': typeof VerifyEmailRoute
  '/$organization/dashboard': typeof OrganizationProtectedOrganizationDashboardRoute
  '/$organization/inbox': typeof OrganizationProtectedOrganizationInboxRoute
  '/$organization/live-visitor': typeof OrganizationProtectedOrganizationLiveVisitorRoute
  '/$organization/plugins': typeof OrganizationProtectedOrganizationPluginsRoute
  '/$organization/settings': typeof OrganizationProtectedOrganizationSettingsRouteWithChildren
  '/$organization/ticket': typeof OrganizationProtectedOrganizationTicketRoute
  '/$organization/visitor': typeof OrganizationProtectedOrganizationVisitorRoute
  '/$organization/settings/team-management': typeof OrganizationProtectedOrganizationSettingsTeamManagementRoute
  '/$organization/settings/account-settings/account-information': typeof OrganizationProtectedOrganizationSettingsAccountSettingsAccountInformationRoute
  '/$organization/settings/account-settings/security': typeof OrganizationProtectedOrganizationSettingsAccountSettingsSecurityRoute
  '/$organization/settings/organization-settings/organization-information': typeof OrganizationProtectedOrganizationSettingsOrganizationSettingsOrganizationInformationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_organization-protected': typeof OrganizationProtectedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/verify': typeof VerifyRouteWithChildren
  '/_organization-protected/$organization': typeof OrganizationProtectedOrganizationRouteWithChildren
  '/_organization-protected/select-organization': typeof OrganizationProtectedSelectOrganizationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/onboarding/organization': typeof OnboardingOrganizationRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/onboarding/user': typeof OnboardingUserRoute
  '/verify/email': typeof VerifyEmailRoute
  '/_organization-protected/$organization/dashboard': typeof OrganizationProtectedOrganizationDashboardRoute
  '/_organization-protected/$organization/inbox': typeof OrganizationProtectedOrganizationInboxRoute
  '/_organization-protected/$organization/live-visitor': typeof OrganizationProtectedOrganizationLiveVisitorRoute
  '/_organization-protected/$organization/plugins': typeof OrganizationProtectedOrganizationPluginsRoute
  '/_organization-protected/$organization/settings': typeof OrganizationProtectedOrganizationSettingsRouteWithChildren
  '/_organization-protected/$organization/ticket': typeof OrganizationProtectedOrganizationTicketRoute
  '/_organization-protected/$organization/visitor': typeof OrganizationProtectedOrganizationVisitorRoute
  '/_organization-protected/$organization/settings/team-management': typeof OrganizationProtectedOrganizationSettingsTeamManagementRoute
  '/_organization-protected/$organization/settings/account-settings/account-information': typeof OrganizationProtectedOrganizationSettingsAccountSettingsAccountInformationRoute
  '/_organization-protected/$organization/settings/account-settings/security': typeof OrganizationProtectedOrganizationSettingsAccountSettingsSecurityRoute
  '/_organization-protected/$organization/settings/organization-settings/organization-information': typeof OrganizationProtectedOrganizationSettingsOrganizationSettingsOrganizationInformationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/verify'
    | '/$organization'
    | '/select-organization'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/set-password'
    | '/onboarding/organization'
    | '/onboarding/success'
    | '/onboarding/user'
    | '/verify/email'
    | '/$organization/dashboard'
    | '/$organization/inbox'
    | '/$organization/live-visitor'
    | '/$organization/plugins'
    | '/$organization/settings'
    | '/$organization/ticket'
    | '/$organization/visitor'
    | '/$organization/settings/team-management'
    | '/$organization/settings/account-settings/account-information'
    | '/$organization/settings/account-settings/security'
    | '/$organization/settings/organization-settings/organization-information'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/verify'
    | '/$organization'
    | '/select-organization'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/set-password'
    | '/onboarding/organization'
    | '/onboarding/success'
    | '/onboarding/user'
    | '/verify/email'
    | '/$organization/dashboard'
    | '/$organization/inbox'
    | '/$organization/live-visitor'
    | '/$organization/plugins'
    | '/$organization/settings'
    | '/$organization/ticket'
    | '/$organization/visitor'
    | '/$organization/settings/team-management'
    | '/$organization/settings/account-settings/account-information'
    | '/$organization/settings/account-settings/security'
    | '/$organization/settings/organization-settings/organization-information'
  id:
    | '__root__'
    | '/'
    | '/_organization-protected'
    | '/auth'
    | '/onboarding'
    | '/verify'
    | '/_organization-protected/$organization'
    | '/_organization-protected/select-organization'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/set-password'
    | '/onboarding/organization'
    | '/onboarding/success'
    | '/onboarding/user'
    | '/verify/email'
    | '/_organization-protected/$organization/dashboard'
    | '/_organization-protected/$organization/inbox'
    | '/_organization-protected/$organization/live-visitor'
    | '/_organization-protected/$organization/plugins'
    | '/_organization-protected/$organization/settings'
    | '/_organization-protected/$organization/ticket'
    | '/_organization-protected/$organization/visitor'
    | '/_organization-protected/$organization/settings/team-management'
    | '/_organization-protected/$organization/settings/account-settings/account-information'
    | '/_organization-protected/$organization/settings/account-settings/security'
    | '/_organization-protected/$organization/settings/organization-settings/organization-information'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrganizationProtectedRoute: typeof OrganizationProtectedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  VerifyRoute: typeof VerifyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_organization-protected': {
      id: '/_organization-protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OrganizationProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/email': {
      id: '/verify/email'
      path: '/email'
      fullPath: '/verify/email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof VerifyRoute
    }
    '/onboarding/user': {
      id: '/onboarding/user'
      path: '/user'
      fullPath: '/onboarding/user'
      preLoaderRoute: typeof OnboardingUserRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/success': {
      id: '/onboarding/success'
      path: '/success'
      fullPath: '/onboarding/success'
      preLoaderRoute: typeof OnboardingSuccessRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/organization': {
      id: '/onboarding/organization'
      path: '/organization'
      fullPath: '/onboarding/organization'
      preLoaderRoute: typeof OnboardingOrganizationRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/auth/set-password': {
      id: '/auth/set-password'
      path: '/set-password'
      fullPath: '/auth/set-password'
      preLoaderRoute: typeof AuthSetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_organization-protected/select-organization': {
      id: '/_organization-protected/select-organization'
      path: '/select-organization'
      fullPath: '/select-organization'
      preLoaderRoute: typeof OrganizationProtectedSelectOrganizationRouteImport
      parentRoute: typeof OrganizationProtectedRoute
    }
    '/_organization-protected/$organization': {
      id: '/_organization-protected/$organization'
      path: '/$organization'
      fullPath: '/$organization'
      preLoaderRoute: typeof OrganizationProtectedOrganizationRouteImport
      parentRoute: typeof OrganizationProtectedRoute
    }
    '/_organization-protected/$organization/visitor': {
      id: '/_organization-protected/$organization/visitor'
      path: '/visitor'
      fullPath: '/$organization/visitor'
      preLoaderRoute: typeof OrganizationProtectedOrganizationVisitorRouteImport
      parentRoute: typeof OrganizationProtectedOrganizationRoute
    }
    '/_organization-protected/$organization/ticket': {
      id: '/_organization-protected/$organization/ticket'
      path: '/ticket'
      fullPath: '/$organization/ticket'
      preLoaderRoute: typeof OrganizationProtectedOrganizationTicketRouteImport
      parentRoute: typeof OrganizationProtectedOrganizationRoute
    }
    '/_organization-protected/$organization/settings': {
      id: '/_organization-protected/$organization/settings'
      path: '/settings'
      fullPath: '/$organization/settings'
      preLoaderRoute: typeof OrganizationProtectedOrganizationSettingsRouteImport
      parentRoute: typeof OrganizationProtectedOrganizationRoute
    }
    '/_organization-protected/$organization/plugins': {
      id: '/_organization-protected/$organization/plugins'
      path: '/plugins'
      fullPath: '/$organization/plugins'
      preLoaderRoute: typeof OrganizationProtectedOrganizationPluginsRouteImport
      parentRoute: typeof OrganizationProtectedOrganizationRoute
    }
    '/_organization-protected/$organization/live-visitor': {
      id: '/_organization-protected/$organization/live-visitor'
      path: '/live-visitor'
      fullPath: '/$organization/live-visitor'
      preLoaderRoute: typeof OrganizationProtectedOrganizationLiveVisitorRouteImport
      parentRoute: typeof OrganizationProtectedOrganizationRoute
    }
    '/_organization-protected/$organization/inbox': {
      id: '/_organization-protected/$organization/inbox'
      path: '/inbox'
      fullPath: '/$organization/inbox'
      preLoaderRoute: typeof OrganizationProtectedOrganizationInboxRouteImport
      parentRoute: typeof OrganizationProtectedOrganizationRoute
    }
    '/_organization-protected/$organization/dashboard': {
      id: '/_organization-protected/$organization/dashboard'
      path: '/dashboard'
      fullPath: '/$organization/dashboard'
      preLoaderRoute: typeof OrganizationProtectedOrganizationDashboardRouteImport
      parentRoute: typeof OrganizationProtectedOrganizationRoute
    }
    '/_organization-protected/$organization/settings/team-management': {
      id: '/_organization-protected/$organization/settings/team-management'
      path: '/team-management'
      fullPath: '/$organization/settings/team-management'
      preLoaderRoute: typeof OrganizationProtectedOrganizationSettingsTeamManagementRouteImport
      parentRoute: typeof OrganizationProtectedOrganizationSettingsRoute
    }
    '/_organization-protected/$organization/settings/organization-settings/organization-information': {
      id: '/_organization-protected/$organization/settings/organization-settings/organization-information'
      path: '/organization-settings/organization-information'
      fullPath: '/$organization/settings/organization-settings/organization-information'
      preLoaderRoute: typeof OrganizationProtectedOrganizationSettingsOrganizationSettingsOrganizationInformationRouteImport
      parentRoute: typeof OrganizationProtectedOrganizationSettingsRoute
    }
    '/_organization-protected/$organization/settings/account-settings/security': {
      id: '/_organization-protected/$organization/settings/account-settings/security'
      path: '/account-settings/security'
      fullPath: '/$organization/settings/account-settings/security'
      preLoaderRoute: typeof OrganizationProtectedOrganizationSettingsAccountSettingsSecurityRouteImport
      parentRoute: typeof OrganizationProtectedOrganizationSettingsRoute
    }
    '/_organization-protected/$organization/settings/account-settings/account-information': {
      id: '/_organization-protected/$organization/settings/account-settings/account-information'
      path: '/account-settings/account-information'
      fullPath: '/$organization/settings/account-settings/account-information'
      preLoaderRoute: typeof OrganizationProtectedOrganizationSettingsAccountSettingsAccountInformationRouteImport
      parentRoute: typeof OrganizationProtectedOrganizationSettingsRoute
    }
  }
}

interface OrganizationProtectedOrganizationSettingsRouteChildren {
  OrganizationProtectedOrganizationSettingsTeamManagementRoute: typeof OrganizationProtectedOrganizationSettingsTeamManagementRoute
  OrganizationProtectedOrganizationSettingsAccountSettingsAccountInformationRoute: typeof OrganizationProtectedOrganizationSettingsAccountSettingsAccountInformationRoute
  OrganizationProtectedOrganizationSettingsAccountSettingsSecurityRoute: typeof OrganizationProtectedOrganizationSettingsAccountSettingsSecurityRoute
  OrganizationProtectedOrganizationSettingsOrganizationSettingsOrganizationInformationRoute: typeof OrganizationProtectedOrganizationSettingsOrganizationSettingsOrganizationInformationRoute
}

const OrganizationProtectedOrganizationSettingsRouteChildren: OrganizationProtectedOrganizationSettingsRouteChildren =
  {
    OrganizationProtectedOrganizationSettingsTeamManagementRoute:
      OrganizationProtectedOrganizationSettingsTeamManagementRoute,
    OrganizationProtectedOrganizationSettingsAccountSettingsAccountInformationRoute:
      OrganizationProtectedOrganizationSettingsAccountSettingsAccountInformationRoute,
    OrganizationProtectedOrganizationSettingsAccountSettingsSecurityRoute:
      OrganizationProtectedOrganizationSettingsAccountSettingsSecurityRoute,
    OrganizationProtectedOrganizationSettingsOrganizationSettingsOrganizationInformationRoute:
      OrganizationProtectedOrganizationSettingsOrganizationSettingsOrganizationInformationRoute,
  }

const OrganizationProtectedOrganizationSettingsRouteWithChildren =
  OrganizationProtectedOrganizationSettingsRoute._addFileChildren(
    OrganizationProtectedOrganizationSettingsRouteChildren,
  )

interface OrganizationProtectedOrganizationRouteChildren {
  OrganizationProtectedOrganizationDashboardRoute: typeof OrganizationProtectedOrganizationDashboardRoute
  OrganizationProtectedOrganizationInboxRoute: typeof OrganizationProtectedOrganizationInboxRoute
  OrganizationProtectedOrganizationLiveVisitorRoute: typeof OrganizationProtectedOrganizationLiveVisitorRoute
  OrganizationProtectedOrganizationPluginsRoute: typeof OrganizationProtectedOrganizationPluginsRoute
  OrganizationProtectedOrganizationSettingsRoute: typeof OrganizationProtectedOrganizationSettingsRouteWithChildren
  OrganizationProtectedOrganizationTicketRoute: typeof OrganizationProtectedOrganizationTicketRoute
  OrganizationProtectedOrganizationVisitorRoute: typeof OrganizationProtectedOrganizationVisitorRoute
}

const OrganizationProtectedOrganizationRouteChildren: OrganizationProtectedOrganizationRouteChildren =
  {
    OrganizationProtectedOrganizationDashboardRoute:
      OrganizationProtectedOrganizationDashboardRoute,
    OrganizationProtectedOrganizationInboxRoute:
      OrganizationProtectedOrganizationInboxRoute,
    OrganizationProtectedOrganizationLiveVisitorRoute:
      OrganizationProtectedOrganizationLiveVisitorRoute,
    OrganizationProtectedOrganizationPluginsRoute:
      OrganizationProtectedOrganizationPluginsRoute,
    OrganizationProtectedOrganizationSettingsRoute:
      OrganizationProtectedOrganizationSettingsRouteWithChildren,
    OrganizationProtectedOrganizationTicketRoute:
      OrganizationProtectedOrganizationTicketRoute,
    OrganizationProtectedOrganizationVisitorRoute:
      OrganizationProtectedOrganizationVisitorRoute,
  }

const OrganizationProtectedOrganizationRouteWithChildren =
  OrganizationProtectedOrganizationRoute._addFileChildren(
    OrganizationProtectedOrganizationRouteChildren,
  )

interface OrganizationProtectedRouteChildren {
  OrganizationProtectedOrganizationRoute: typeof OrganizationProtectedOrganizationRouteWithChildren
  OrganizationProtectedSelectOrganizationRoute: typeof OrganizationProtectedSelectOrganizationRoute
}

const OrganizationProtectedRouteChildren: OrganizationProtectedRouteChildren = {
  OrganizationProtectedOrganizationRoute:
    OrganizationProtectedOrganizationRouteWithChildren,
  OrganizationProtectedSelectOrganizationRoute:
    OrganizationProtectedSelectOrganizationRoute,
}

const OrganizationProtectedRouteWithChildren =
  OrganizationProtectedRoute._addFileChildren(
    OrganizationProtectedRouteChildren,
  )

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthSetPasswordRoute: typeof AuthSetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthSetPasswordRoute: AuthSetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface OnboardingRouteChildren {
  OnboardingOrganizationRoute: typeof OnboardingOrganizationRoute
  OnboardingSuccessRoute: typeof OnboardingSuccessRoute
  OnboardingUserRoute: typeof OnboardingUserRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingOrganizationRoute: OnboardingOrganizationRoute,
  OnboardingSuccessRoute: OnboardingSuccessRoute,
  OnboardingUserRoute: OnboardingUserRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface VerifyRouteChildren {
  VerifyEmailRoute: typeof VerifyEmailRoute
}

const VerifyRouteChildren: VerifyRouteChildren = {
  VerifyEmailRoute: VerifyEmailRoute,
}

const VerifyRouteWithChildren =
  VerifyRoute._addFileChildren(VerifyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrganizationProtectedRoute: OrganizationProtectedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  VerifyRoute: VerifyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
