/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as VerifyRouteImport } from './routes/_verify'
import { Route as OrganizationProtectedRouteImport } from './routes/_organization-protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyVerifyMfaRouteImport } from './routes/_verify/verify-mfa'
import { Route as VerifyVerifyEmailRouteImport } from './routes/_verify/verify-email'
import { Route as OrganizationProtectedSelectOrganizationRouteImport } from './routes/_organization-protected/select-organization'
import { Route as OrganizationProtectedOrganizationRouteImport } from './routes/_organization-protected/$organization'
import { Route as AuthSetPasswordRouteImport } from './routes/_auth/set-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as OrganizationProtectedOrganizationVisitorRouteImport } from './routes/_organization-protected/$organization/visitor'
import { Route as OrganizationProtectedOrganizationTicketRouteImport } from './routes/_organization-protected/$organization/ticket'
import { Route as OrganizationProtectedOrganizationInboxRouteImport } from './routes/_organization-protected/$organization/inbox'
import { Route as OrganizationProtectedOrganizationDashboardRouteImport } from './routes/_organization-protected/$organization/dashboard'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/_verify',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationProtectedRoute = OrganizationProtectedRouteImport.update({
  id: '/_organization-protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyVerifyMfaRoute = VerifyVerifyMfaRouteImport.update({
  id: '/verify-mfa',
  path: '/verify-mfa',
  getParentRoute: () => VerifyRoute,
} as any)
const VerifyVerifyEmailRoute = VerifyVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => VerifyRoute,
} as any)
const OrganizationProtectedSelectOrganizationRoute =
  OrganizationProtectedSelectOrganizationRouteImport.update({
    id: '/select-organization',
    path: '/select-organization',
    getParentRoute: () => OrganizationProtectedRoute,
  } as any)
const OrganizationProtectedOrganizationRoute =
  OrganizationProtectedOrganizationRouteImport.update({
    id: '/$organization',
    path: '/$organization',
    getParentRoute: () => OrganizationProtectedRoute,
  } as any)
const AuthSetPasswordRoute = AuthSetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const OrganizationProtectedOrganizationVisitorRoute =
  OrganizationProtectedOrganizationVisitorRouteImport.update({
    id: '/visitor',
    path: '/visitor',
    getParentRoute: () => OrganizationProtectedOrganizationRoute,
  } as any)
const OrganizationProtectedOrganizationTicketRoute =
  OrganizationProtectedOrganizationTicketRouteImport.update({
    id: '/ticket',
    path: '/ticket',
    getParentRoute: () => OrganizationProtectedOrganizationRoute,
  } as any)
const OrganizationProtectedOrganizationInboxRoute =
  OrganizationProtectedOrganizationInboxRouteImport.update({
    id: '/inbox',
    path: '/inbox',
    getParentRoute: () => OrganizationProtectedOrganizationRoute,
  } as any)
const OrganizationProtectedOrganizationDashboardRoute =
  OrganizationProtectedOrganizationDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => OrganizationProtectedOrganizationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/set-password': typeof AuthSetPasswordRoute
  '/$organization': typeof OrganizationProtectedOrganizationRouteWithChildren
  '/select-organization': typeof OrganizationProtectedSelectOrganizationRoute
  '/verify-email': typeof VerifyVerifyEmailRoute
  '/verify-mfa': typeof VerifyVerifyMfaRoute
  '/$organization/dashboard': typeof OrganizationProtectedOrganizationDashboardRoute
  '/$organization/inbox': typeof OrganizationProtectedOrganizationInboxRoute
  '/$organization/ticket': typeof OrganizationProtectedOrganizationTicketRoute
  '/$organization/visitor': typeof OrganizationProtectedOrganizationVisitorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/set-password': typeof AuthSetPasswordRoute
  '/$organization': typeof OrganizationProtectedOrganizationRouteWithChildren
  '/select-organization': typeof OrganizationProtectedSelectOrganizationRoute
  '/verify-email': typeof VerifyVerifyEmailRoute
  '/verify-mfa': typeof VerifyVerifyMfaRoute
  '/$organization/dashboard': typeof OrganizationProtectedOrganizationDashboardRoute
  '/$organization/inbox': typeof OrganizationProtectedOrganizationInboxRoute
  '/$organization/ticket': typeof OrganizationProtectedOrganizationTicketRoute
  '/$organization/visitor': typeof OrganizationProtectedOrganizationVisitorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_organization-protected': typeof OrganizationProtectedRouteWithChildren
  '/_verify': typeof VerifyRouteWithChildren
  '/about': typeof AboutRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/set-password': typeof AuthSetPasswordRoute
  '/_organization-protected/$organization': typeof OrganizationProtectedOrganizationRouteWithChildren
  '/_organization-protected/select-organization': typeof OrganizationProtectedSelectOrganizationRoute
  '/_verify/verify-email': typeof VerifyVerifyEmailRoute
  '/_verify/verify-mfa': typeof VerifyVerifyMfaRoute
  '/_organization-protected/$organization/dashboard': typeof OrganizationProtectedOrganizationDashboardRoute
  '/_organization-protected/$organization/inbox': typeof OrganizationProtectedOrganizationInboxRoute
  '/_organization-protected/$organization/ticket': typeof OrganizationProtectedOrganizationTicketRoute
  '/_organization-protected/$organization/visitor': typeof OrganizationProtectedOrganizationVisitorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/set-password'
    | '/$organization'
    | '/select-organization'
    | '/verify-email'
    | '/verify-mfa'
    | '/$organization/dashboard'
    | '/$organization/inbox'
    | '/$organization/ticket'
    | '/$organization/visitor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/set-password'
    | '/$organization'
    | '/select-organization'
    | '/verify-email'
    | '/verify-mfa'
    | '/$organization/dashboard'
    | '/$organization/inbox'
    | '/$organization/ticket'
    | '/$organization/visitor'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_organization-protected'
    | '/_verify'
    | '/about'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/set-password'
    | '/_organization-protected/$organization'
    | '/_organization-protected/select-organization'
    | '/_verify/verify-email'
    | '/_verify/verify-mfa'
    | '/_organization-protected/$organization/dashboard'
    | '/_organization-protected/$organization/inbox'
    | '/_organization-protected/$organization/ticket'
    | '/_organization-protected/$organization/visitor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  OrganizationProtectedRoute: typeof OrganizationProtectedRouteWithChildren
  VerifyRoute: typeof VerifyRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_verify': {
      id: '/_verify'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_organization-protected': {
      id: '/_organization-protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OrganizationProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_verify/verify-mfa': {
      id: '/_verify/verify-mfa'
      path: '/verify-mfa'
      fullPath: '/verify-mfa'
      preLoaderRoute: typeof VerifyVerifyMfaRouteImport
      parentRoute: typeof VerifyRoute
    }
    '/_verify/verify-email': {
      id: '/_verify/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyVerifyEmailRouteImport
      parentRoute: typeof VerifyRoute
    }
    '/_organization-protected/select-organization': {
      id: '/_organization-protected/select-organization'
      path: '/select-organization'
      fullPath: '/select-organization'
      preLoaderRoute: typeof OrganizationProtectedSelectOrganizationRouteImport
      parentRoute: typeof OrganizationProtectedRoute
    }
    '/_organization-protected/$organization': {
      id: '/_organization-protected/$organization'
      path: '/$organization'
      fullPath: '/$organization'
      preLoaderRoute: typeof OrganizationProtectedOrganizationRouteImport
      parentRoute: typeof OrganizationProtectedRoute
    }
    '/_auth/set-password': {
      id: '/_auth/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof AuthSetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_organization-protected/$organization/visitor': {
      id: '/_organization-protected/$organization/visitor'
      path: '/visitor'
      fullPath: '/$organization/visitor'
      preLoaderRoute: typeof OrganizationProtectedOrganizationVisitorRouteImport
      parentRoute: typeof OrganizationProtectedOrganizationRoute
    }
    '/_organization-protected/$organization/ticket': {
      id: '/_organization-protected/$organization/ticket'
      path: '/ticket'
      fullPath: '/$organization/ticket'
      preLoaderRoute: typeof OrganizationProtectedOrganizationTicketRouteImport
      parentRoute: typeof OrganizationProtectedOrganizationRoute
    }
    '/_organization-protected/$organization/inbox': {
      id: '/_organization-protected/$organization/inbox'
      path: '/inbox'
      fullPath: '/$organization/inbox'
      preLoaderRoute: typeof OrganizationProtectedOrganizationInboxRouteImport
      parentRoute: typeof OrganizationProtectedOrganizationRoute
    }
    '/_organization-protected/$organization/dashboard': {
      id: '/_organization-protected/$organization/dashboard'
      path: '/dashboard'
      fullPath: '/$organization/dashboard'
      preLoaderRoute: typeof OrganizationProtectedOrganizationDashboardRouteImport
      parentRoute: typeof OrganizationProtectedOrganizationRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthSetPasswordRoute: typeof AuthSetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthSetPasswordRoute: AuthSetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface OrganizationProtectedOrganizationRouteChildren {
  OrganizationProtectedOrganizationDashboardRoute: typeof OrganizationProtectedOrganizationDashboardRoute
  OrganizationProtectedOrganizationInboxRoute: typeof OrganizationProtectedOrganizationInboxRoute
  OrganizationProtectedOrganizationTicketRoute: typeof OrganizationProtectedOrganizationTicketRoute
  OrganizationProtectedOrganizationVisitorRoute: typeof OrganizationProtectedOrganizationVisitorRoute
}

const OrganizationProtectedOrganizationRouteChildren: OrganizationProtectedOrganizationRouteChildren =
  {
    OrganizationProtectedOrganizationDashboardRoute:
      OrganizationProtectedOrganizationDashboardRoute,
    OrganizationProtectedOrganizationInboxRoute:
      OrganizationProtectedOrganizationInboxRoute,
    OrganizationProtectedOrganizationTicketRoute:
      OrganizationProtectedOrganizationTicketRoute,
    OrganizationProtectedOrganizationVisitorRoute:
      OrganizationProtectedOrganizationVisitorRoute,
  }

const OrganizationProtectedOrganizationRouteWithChildren =
  OrganizationProtectedOrganizationRoute._addFileChildren(
    OrganizationProtectedOrganizationRouteChildren,
  )

interface OrganizationProtectedRouteChildren {
  OrganizationProtectedOrganizationRoute: typeof OrganizationProtectedOrganizationRouteWithChildren
  OrganizationProtectedSelectOrganizationRoute: typeof OrganizationProtectedSelectOrganizationRoute
}

const OrganizationProtectedRouteChildren: OrganizationProtectedRouteChildren = {
  OrganizationProtectedOrganizationRoute:
    OrganizationProtectedOrganizationRouteWithChildren,
  OrganizationProtectedSelectOrganizationRoute:
    OrganizationProtectedSelectOrganizationRoute,
}

const OrganizationProtectedRouteWithChildren =
  OrganizationProtectedRoute._addFileChildren(
    OrganizationProtectedRouteChildren,
  )

interface VerifyRouteChildren {
  VerifyVerifyEmailRoute: typeof VerifyVerifyEmailRoute
  VerifyVerifyMfaRoute: typeof VerifyVerifyMfaRoute
}

const VerifyRouteChildren: VerifyRouteChildren = {
  VerifyVerifyEmailRoute: VerifyVerifyEmailRoute,
  VerifyVerifyMfaRoute: VerifyVerifyMfaRoute,
}

const VerifyRouteWithChildren =
  VerifyRoute._addFileChildren(VerifyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  OrganizationProtectedRoute: OrganizationProtectedRouteWithChildren,
  VerifyRoute: VerifyRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
