// Auto-generated by generate-types.ts
import type { ReactElement, SVGProps } from 'react';

import AccountSecurity from './icons/account-security';
import Accounts from './icons/accounts';
import AddAttatchments from './icons/add-attatchments';
import Alert from './icons/alert';
import AllAgent from './icons/all-agent';
import AllConversation from './icons/all-conversation';
import AllInsights from './icons/all-insights';
import AllRoles from './icons/all-roles';
import Analytics from './icons/analytics';
import ArrowDown from './icons/arrow-down';
import ArrowLeft from './icons/arrow-left';
import ArrowRight from './icons/arrow-right';
import ArrowUp from './icons/arrow-up';
import Assignee from './icons/assignee';
import Audio from './icons/audio';
import AutoComplete from './icons/auto-complete';
import Back from './icons/back';
import BanVisitor from './icons/ban-visitor';
import Bold from './icons/bold';
import Browser from './icons/browser';
import Bullet from './icons/bullet';
import Calender from './icons/calender';
import Call from './icons/call';
import Campaigns from './icons/campaigns';
import Channels from './icons/channels';
import ChatboqAi from './icons/chatboq-ai';
import ChatboqLogo from './icons/chatboq-logo';
import ChatboqSettings from './icons/chatboq-settings';
import Chrome from './icons/chrome';
import Close from './icons/close';
import Command from './icons/command';
import Computer from './icons/computer';
import ConfirmPassword from './icons/confirm-password';
import Contacts from './icons/contacts';
import Copilot from './icons/copilot';
import Copy from './icons/copy';
import CustomerWaiting from './icons/customer-waiting';
import CustomerWaitingGradient from './icons/customer-waiting-gradient';
import Deactivate from './icons/deactivate';
import Delete from './icons/delete';
import Department from './icons/department';
import Done from './icons/done';
import Dot from './icons/dot';
import Drag from './icons/drag';
import DualArrow from './icons/dual-arrow';
import Edit from './icons/edit';
import Elaborate from './icons/elaborate';
import Email from './icons/email';
import EyeOff from './icons/eye-off';
import EyeOn from './icons/eye-on';
import Feedback from './icons/feedback';
import File from './icons/file';
import Filter from './icons/filter';
import FixGrammar from './icons/fix-grammar';
import FormalTone from './icons/formal-tone';
import Formatting from './icons/formatting';
import FriendlyTone from './icons/friendly-tone';
import FullScreen from './icons/full-screen';
import Gmt from './icons/gmt';
import Google from './icons/google';
import Home from './icons/home';
import Horizontal3DotMenu from './icons/horizontal-3-dot-menu';
import ImagePlaceHolder from './icons/image-place-holder';
import Inbox from './icons/inbox';
import Instagram from './icons/instagram';
import Italic from './icons/italic';
import K from './icons/k';
import KnowledgeBaseGradient from './icons/knowledge-base-gradient';
import KnowledgeHub from './icons/knowledge-hub';
import Laptop from './icons/laptop';
import Link from './icons/link';
import Linkedin from './icons/linkedin';
import ListView from './icons/list-view';
import Load from './icons/load';
import Location from './icons/location';
import Lock from './icons/lock';
import Logout from './icons/logout';
import LongArrowRight from './icons/long-arrow-right';
import LookingIntoIssue from './icons/looking-into-issue';
import MagicBrowse from './icons/magic-browse';
import MainSearch from './icons/main-search';
import Mentions from './icons/mentions';
import Messenger from './icons/messenger';
import More from './icons/more';
import Motivations from './icons/motivations';
import Music from './icons/music';
import Note from './icons/note';
import Notifications from './icons/notifications';
import NumberedList from './icons/numbered-list';
import Offline from './icons/offline';
import OnlineOnly from './icons/online-only';
import OtherConversations from './icons/other-conversations';
import PendingInvite from './icons/pending-invite';
import Pin from './icons/pin';
import PinOff from './icons/pin-off';
import Pinned from './icons/pinned';
import Plan from './icons/plan';
import Plugins from './icons/plugins';
import Plus from './icons/plus';
import QuickReply from './icons/quick-reply';
import Refresh from './icons/refresh';
import Rephrase from './icons/rephrase';
import Reply from './icons/reply';
import ReplyMenu from './icons/reply-menu';
import RequestFeedback from './icons/request-feedback';
import Resolved from './icons/resolved';
import Role from './icons/role';
import Safari from './icons/safari';
import Search from './icons/search';
import Send from './icons/send';
import SendEmojis from './icons/send-emojis';
import SendToCustomer from './icons/send-to-customer';
import SendTranscript from './icons/send-transcript';
import SetReminder from './icons/set-reminder';
import Settings from './icons/settings';
import SetupInstruction from './icons/setup-instruction';
import Shortcuts from './icons/shortcuts';
import SidebarClose from './icons/sidebar-close';
import SidebarOpen from './icons/sidebar-open';
import Signature from './icons/signature';
import SmartPhone from './icons/smart-phone';
import Snooze from './icons/snooze';
import StatusUpdate from './icons/status-update';
import Step1 from './icons/step-1';
import Step2 from './icons/step-2';
import Step3 from './icons/step-3';
import Support from './icons/support';
import SupportLibrary from './icons/support-library';
import Sync from './icons/sync';
import Team from './icons/team';
import Telegram from './icons/telegram';
import Tick from './icons/tick';
import Tickets from './icons/tickets';
import Time from './icons/time';
import Transfer from './icons/transfer';
import Twitter from './icons/twitter';
import Unassigned from './icons/unassigned';
import Underline from './icons/underline';
import Unread from './icons/unread';
import Unresolved from './icons/unresolved';
import Upgrade from './icons/upgrade';
import Vertical3DotMenu from './icons/vertical-3-dot-menu';
import VideoCall from './icons/video-call';
import Vip from './icons/vip';
import Whatsapp from './icons/whatsapp';
import Workspace from './icons/workspace';
import type { IconName } from './types';

export type IconComponent = (props: SVGProps<SVGSVGElement>) => ReactElement;

export const iconMap = {
  'account-security': AccountSecurity,
  accounts: Accounts,
  'add-attatchments': AddAttatchments,
  alert: Alert,
  'all-agent': AllAgent,
  'all-conversation': AllConversation,
  'all-insights': AllInsights,
  'all-roles': AllRoles,
  analytics: Analytics,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  assignee: Assignee,
  audio: Audio,
  'auto-complete': AutoComplete,
  back: Back,
  'ban-visitor': BanVisitor,
  bold: Bold,
  browser: Browser,
  bullet: Bullet,
  calender: Calender,
  call: Call,
  campaigns: Campaigns,
  channels: Channels,
  'chatboq-ai': ChatboqAi,
  'chatboq-logo': ChatboqLogo,
  'chatboq-settings': ChatboqSettings,
  chrome: Chrome,
  close: Close,
  command: Command,
  computer: Computer,
  'confirm-password': ConfirmPassword,
  contacts: Contacts,
  copilot: Copilot,
  copy: Copy,
  'customer-waiting': CustomerWaiting,
  'customer-waiting-gradient': CustomerWaitingGradient,
  deactivate: Deactivate,
  delete: Delete,
  department: Department,
  done: Done,
  dot: Dot,
  drag: Drag,
  'dual-arrow': DualArrow,
  edit: Edit,
  elaborate: Elaborate,
  email: Email,
  'eye-off': EyeOff,
  'eye-on': EyeOn,
  feedback: Feedback,
  file: File,
  filter: Filter,
  'fix-grammar': FixGrammar,
  'formal-tone': FormalTone,
  formatting: Formatting,
  'friendly-tone': FriendlyTone,
  'full-screen': FullScreen,
  gmt: Gmt,
  google: Google,
  home: Home,
  'horizontal-3-dot-menu': Horizontal3DotMenu,
  'image-place-holder': ImagePlaceHolder,
  inbox: Inbox,
  instagram: Instagram,
  italic: Italic,
  k: K,
  'knowledge-base-gradient': KnowledgeBaseGradient,
  'knowledge-hub': KnowledgeHub,
  laptop: Laptop,
  link: Link,
  linkedin: Linkedin,
  'list-view': ListView,
  load: Load,
  location: Location,
  lock: Lock,
  logout: Logout,
  'long-arrow-right': LongArrowRight,
  'looking-into-issue': LookingIntoIssue,
  'magic-browse': MagicBrowse,
  'main-search': MainSearch,
  mentions: Mentions,
  messenger: Messenger,
  more: More,
  motivations: Motivations,
  music: Music,
  note: Note,
  notifications: Notifications,
  'numbered-list': NumberedList,
  offline: Offline,
  'online-only': OnlineOnly,
  'other-conversations': OtherConversations,
  'pending-invite': PendingInvite,
  pin: Pin,
  'pin-off': PinOff,
  pinned: Pinned,
  plan: Plan,
  plugins: Plugins,
  plus: Plus,
  'quick-reply': QuickReply,
  refresh: Refresh,
  rephrase: Rephrase,
  reply: Reply,
  'reply-menu': ReplyMenu,
  'request-feedback': RequestFeedback,
  resolved: Resolved,
  role: Role,
  safari: Safari,
  search: Search,
  send: Send,
  'send-emojis': SendEmojis,
  'send-to-customer': SendToCustomer,
  'send-transcript': SendTranscript,
  'set-reminder': SetReminder,
  settings: Settings,
  'setup-instruction': SetupInstruction,
  shortcuts: Shortcuts,
  'sidebar-close': SidebarClose,
  'sidebar-open': SidebarOpen,
  signature: Signature,
  'smart-phone': SmartPhone,
  snooze: Snooze,
  'status-update': StatusUpdate,
  'step-1': Step1,
  'step-2': Step2,
  'step-3': Step3,
  support: Support,
  'support-library': SupportLibrary,
  sync: Sync,
  team: Team,
  telegram: Telegram,
  tick: Tick,
  tickets: Tickets,
  time: Time,
  transfer: Transfer,
  twitter: Twitter,
  unassigned: Unassigned,
  underline: Underline,
  unread: Unread,
  unresolved: Unresolved,
  upgrade: Upgrade,
  'vertical-3-dot-menu': Vertical3DotMenu,
  'video-call': VideoCall,
  vip: Vip,
  whatsapp: Whatsapp,
  workspace: Workspace,
} satisfies Record<IconName, IconComponent>;
