import * as fs from 'fs';
import * as path from 'path';

const iconsDir = path.join(__dirname, '../src/icons');
const srcDir = path.join(__dirname, '../src');

if (!fs.existsSync(iconsDir)) {
  fs.mkdirSync(iconsDir, { recursive: true });
}

const files = fs.readdirSync(iconsDir);

const namesArray = files
  .filter((file: string) => file.endsWith('.tsx') && file !== 'index.tsx')
  .map((file: string) => file.replace('.tsx', ''))
  .sort();

const toPascalCase = (name: string) =>
  name
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');

const namesList = namesArray.map((name) => `  "${name}"`).join(',\n');

const typesContent = `// Auto-generated by generate-types.ts

export const ICON_NAMES = [
${namesList}
] as const

export type IconName = (typeof ICON_NAMES)[number]
`;

fs.writeFileSync(path.join(srcDir, 'types.ts'), typesContent);

const indexContent = namesArray
  .map((name) => `export { default as ${toPascalCase(name)} } from "./${name}"`)
  .join('\n');

fs.writeFileSync(
  path.join(iconsDir, 'index.ts'),
  `// Auto-generated by generate-types.ts\n${indexContent}\n`,
);

const iconImports = namesArray
  .map((name) => `import ${toPascalCase(name)} from "./icons/${name}"`)
  .join('\n');
const iconMapEntries = namesArray
  .map((name) => `  "${name}": ${toPascalCase(name)}`)
  .join(',\n');

const iconMapContent = `// Auto-generated by generate-types.ts
import type { ReactElement, SVGProps } from "react"

${iconImports}
import type { IconName } from "./types"

export type IconComponent = (props: SVGProps<SVGSVGElement>) => ReactElement

export const iconMap = {
${iconMapEntries}
} satisfies Record<IconName, IconComponent>
`;

fs.writeFileSync(path.join(srcDir, 'icon-map.ts'), iconMapContent);
