import type { EditorThemeClasses } from 'lexical';

export const editorTheme: EditorThemeClasses = {
  paragraph: 'mb-0',
  text: {
    bold: 'font-bold',
    italic: 'italic',
    underline: 'underline',
    strikethrough: 'line-through',
    underlineStrikethrough: 'underline line-through',
    code: 'bg-gray-100 px-1 rounded font-mono text-sm',
  },
  heading: {
    h1: 'text-2xl font-bold mb-2',
    h2: 'text-xl font-bold mb-2',
    h3: 'text-lg font-semibold mb-1',
    h4: 'text-base font-semibold mb-1',
    h5: 'text-sm font-semibold mb-1',
  },
  list: {
    nested: { listitem: 'list-none' },
    ul: 'list-disc list-inside mb-2',
    ol: 'list-decimal list-inside mb-2',
    listitem: 'mb-1',
  },
  quote: 'border-l-4 border-gray-300 pl-4 italic mb-2',
  link: 'text-blue-600 underline cursor-pointer',
  code: 'block bg-gray-100 p-3 rounded font-mono text-sm mb-2 overflow-x-auto',
  codeHighlight: {
    atrule: 'text-purple-600',
    attr: 'text-blue-600',
    boolean: 'text-orange-600',
    builtin: 'text-green-600',
    cdata: 'text-gray-600',
    char: 'text-green-600',
    class: 'text-blue-600',
    'class-name': 'text-blue-600',
    comment: 'text-gray-500 italic',
    constant: 'text-purple-600',
    deleted: 'text-red-600',
    doctype: 'text-gray-600',
    entity: 'text-orange-600',
    function: 'text-blue-600',
    important: 'text-orange-600',
    inserted: 'text-green-600',
    keyword: 'text-purple-600',
    namespace: 'text-red-600',
    number: 'text-orange-600',
    operator: 'text-gray-700',
    prolog: 'text-gray-600',
    property: 'text-purple-600',
    punctuation: 'text-gray-600',
    regex: 'text-orange-600',
    selector: 'text-green-600',
    string: 'text-green-600',
    symbol: 'text-purple-600',
    tag: 'text-red-600',
    url: 'text-blue-600',
    variable: 'text-red-600',
  },
};
